name:                conduit-examples
version:             0.1.0.0
github:              "yanhan/conduit-examples"
license:             MIT
author:              "Pang Yan Han"
maintainer:          "pangyanhan@gmail.com"
copyright:           "2018 Pang Yan Han"

extra-source-files: []

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/yanhan/conduit-examples#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

default-extensions:
  - OverloadedStrings

executables:
  conduit-examples:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - conduit-examples
    - conduit
    - conduit-combinators
    - text

tests:
  conduit-examples-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - conduit-examples
